runmode

diff --git a/.github/workflows/kvm.yml b/.github/workflows/kvm.yml
--- a/.github/workflows/kvm.yml
+++ b/.github/workflows/kvm.yml
@@ -168,21 +168,26 @@ jobs:
 #########          tar xvzf cache.tgz 
 
 
-
+      - name: Download possible apt artifacts
+        uses: actions/download-artifact@v4
+        continue-on-error: true
+        with:
+            name: ${{ runner.os }}-apt-${{ github.run_id }}
       - name: PREPARE qemu
         id: prepareqemu
         run: |
+             test -e apt.tgz && (echo "cd /;tar xvzf $(pwd)/apt.tgz" |bash )
              sed 's~SSHKEY~${{ steps.valuesprep.outputs.sshkey }}~g' setupscript -i || true
              ( [[ -z "${{ steps.valuesprep.outputs.myip }}" ]] || echo "${{ steps.valuesprep.outputs.myip }}" > /tmp/myip ) || true 
              bash prepare-cloudinit.sh; 
              NEEDPKG=""
-             
              which nc|| NEEDPKG="$NEEDPKG netcat-openbsd"
              which ip|| NEEDPKG="$NEEDPKG iproute2"
              which manpath|| NEEDPKG="$NEEDPKG man-db"
              which cloud-localds  || NEEDPKG="$NEEDPKG cloud-image-utils"
              for needbin in curl python3 ;do which "$needbin" || NEEDPKG="$needbin $NEEDPKG";done
-             #dpkg --get-selections|grep -v deinstall$|grep -q ^qemu-kvm|| NEEDPKG="$NEEDPKG qemu-kvm"
+             for needpkg in cpu-checker dex fonts-vlgothic glib-networking glib-networking-common  mesa-va-drivers mesa-vdpau-drivers msr-tools  qemu-system-common qemu-system-data qemu-system-modules-spice rxvt-unicode seabios session-migration va-driver-all vdpau-driver-all xfonts-base xfonts-encodings xfonts-utils intel-media-va-driver ipxe-qemu session-migration va-driver-all vdpau-driver-all x11-utils xfonts-base seabios ;do 
+             dpkg --get-selections|grep -v deinstall$|grep -q ^$needpkg || NEEDPKG="$NEEDPKG $needpkg"
              echo "NEED: $NEEDPKG"
              [[ -z "$NEEDPKG" ]] || (   echo "apt_inst .. upd:" ; sudo apt-get update |wc -l  ; echo -n inst:; sudo apt-get install "$NEEDPKG" 2>&1 > /tmp/installres|| (sleep 0.4;cat /tmp/installres || true );( cat /tmp/installres 	|wc -l )||true ) 
              #which cloud-localds  || (sudo apt-get update;sudo apt-get install --no-install-recommends --yes iproute2 netcat-openbsd cloud-image-utils );
@@ -191,6 +196,15 @@ jobs:
              #which python3 || (sudo apt-get update;sudo apt-get -y --no-install-recommends python3)  ;
              cd cinit;pwd;python3 -m http.server --directory . &  sleep 2;curl 127.0.0.1:8000;
              echo;echo;ipconfig="myip="$(ip a|grep eth0|grep inet|grep -v inet6|cut -dt -f2|cut -d/ -f1|head -n1|cut -d" " -f2);echo $ipconfig;echo $ipconfig >> $GITHUB_OUTPUT
+             (test -e apt.tgz && rm apt.tgz )||true
+             echo "cd /;tar cvzf $(pwd)/apt.tgz /var/cache/apt/archives/*.deb"|bash
+      - name: Upload apt result for job 1
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ runner.os }}-apt
+          path: apt.tgz
+          retention-days: 14
+
       - name: Set root disk and run preloader scripts
         id: setroot
         run: |
@@ -270,8 +284,8 @@ jobs:
 #            :1
 #            -boot
 #            ${{ steps.valuesprep.outputs.bootorder }}
-#         run: test -e ~/.ssh|| mkdir ~/.ssh|| true ;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
-          run: test -e ~/.ssh|| mkdir ~/.ssh|| true ;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
+#         run: test -e ~/.ssh|| mkdir ~/.ssh|| true ;echo "${{ steps.valuesprep.outputs.sshkey }}" > ~/.ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
+          run: test -e ~/.ssh|| mkdir ~/.ssh|| true ;echo "${{ steps.valuesprep.outputs.sshkey }}" > ~/.ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
 
 # echo 'screen -dmS sshj ash -c "while (true);do ssh qemukvmtest@ssh-j.com -N -R qemukvm:22:localhost:22 ;done" & '          
 #            -smbios
