runmode

diff --git a/.github/workflows/kvm.yml b/.github/workflows/kvm.yml
--- a/.github/workflows/kvm.yml
+++ b/.github/workflows/kvm.yml
@@ -35,7 +35,7 @@ on:
 jobs:
   setup:
     runs-on: ubuntu-latest
-    container: ghcr.io/its-the-final/gha-kvm:latest
+#    container: ghcr.io/its-the-final/gha-kvm:latest
     steps:
       - uses: actions/checkout@v4
 #      - uses: ilammy/setup-nasm@v1
@@ -87,7 +87,8 @@ jobs:
           #tar --xz -xf debian-11-backports-nocloud-amd64-20250703-2162.tar.xz
           #ln -s debian-11-backports-nocloud-amd64-20250703-2162.raw alpine-x86_64.img
           bash -c "time  qemu-img resize images/machine.qcow2 +${{ steps.valuesprep.outputs.size }}" || true
-          test -e qemu-kvm-action || git clone https://github.com/incredinews/qemu-kvm-action.git
+          test -e qemu-kvm-action || git clone https://github.com/etchdroid/qemu-kvm-action.git
+#          test -e qemu-kvm-action || git clone https://github.com/incredinews/qemu-kvm-action.git
 ########      - name: cachetar
 ########        id: cachetar
 ########        run: |
@@ -108,7 +109,7 @@ jobs:
           path: |
             images
             cdrom
-            /var/cache/apt/archives
+#            /var/cache/apt/archives
           key: ${{ runner.os }}-primes-${{ steps.valuesprep.outputs.imgsum }}
 #          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
 
@@ -218,21 +219,10 @@ jobs:
              #apt-get -y remove ovmf || true
       - name: Run QEMU
         id: run-qemu
-        uses: incredinews/qemu-kvm-action@main
-#        uses: etchdroid/qemu-kvm-action@v1
+#        uses: incredinews/qemu-kvm-action@main
+        uses: etchdroid/qemu-kvm-action@v1
         env:
           TERM: linux
-#        docker_container:
-#          name: android-emulator
-#          image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
-#          pull: true
-#          restart_policy: unless-stopped
-#          devices:
-#            - "/dev/kvm"
-#          ports:
-#            - "2222:22"
-#            - "5901:5901"
-#            - "15901:15901"
         with:
 #          https://github.com/etchdroid/qemu-kvm-action/blob/main/action.yml
           smp: 8
@@ -267,8 +257,8 @@ jobs:
             ${{ steps.valuesprep.outputs.cdrom }}
             -boot
             ${{ steps.valuesprep.outputs.boot }}
-#         run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
-          run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ; echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
+#         run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
+          run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
 
 # echo 'screen -dmS sshj ash -c "while (true);do ssh qemukvmtest@ssh-j.com -N -R qemukvm:22:localhost:22 ;done" & '          
 #            -smbios
