runmode

diff --git a/.github/workflows/kvm.yml b/.github/workflows/kvm.yml
--- a/.github/workflows/kvm.yml
+++ b/.github/workflows/kvm.yml
@@ -128,7 +128,7 @@ jobs:
         id: valuesprep
         run: |
           KEY_INPUT=${{ github.event.inputs.sshkey }}
-          echo sshkey=${IMG_INPUT:-"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQC6cZ/ZGVD547VMy4Cz/sMVAezZsv33woT8v9zCh0WuSIcMZOFIeBhI7oB6L7hwSlGmb2BNFmgJJ5ML0jy6y55rI1X0EaQV9uLTdYcfpcFUu0sbq5/9TAEWqt5EL8R7nxs7Yl8FEfUhG4GAMiDUwJK9oOIHvtzjqdCNYZKOB5JyVc3/tBqtUXbMrGP+ZLuqscxLrdbgQRg6FTOXt8jW48ofYa7nM7tMoFBXIN7wSCPpifme7HnoblHIeoPlGwyLPEiu36pnj6KAKQCZgYenx8Noj99+nnFJorxbtgIL7WMWjt+HlVaiVEZ6A6MbaZbwrhpCiow57bd3zdq3vluZwPZNNCL8AOKXtm7D35aC+wKibur7FyundFNlKpHgTtXRYNEKRj/ulW1z2HKwoU6Ban6X+rSzVmGkBiQyB/G76L8b/eXRh3Hptvbp4nQu15kGhsQXZA7g7Z25yPlmeO7pWMRJRNbohhOM/29PX1c6dH9+WoNJtkHh6Hk1fgTD0JDVxNFarIjmxv0nIQUcr0tdsL2/3o0t7sZwjtZvoFSGqKsZ5PMAqUHjJiDnGwK+GDBOoWWtrtkJXNfSxwl0Zsazj6tN4CG29sUjzss9LWcNTa8zdUhb3RY6OhpWcQaBJi/MmQVKLacwy+KxKfhMEXmNkaVWyX3eCaK1ih9q7wWM6iDWX1pJkmKlroXmRzVaSgfNb1JIRkBtiecOHN+26Bv59TbJcKkYXsbBP6P4m5VqjiJD2xw/VN6sW8Kohu9igBtxNR4ayYqKyIRPE5UbE/kl4x+84C//IfKdnRoLmCwkUauOC8z/5ThMmlASAtIOgAcdQSJRXWyWtQoZnDc5Om3SCejqflkBceQpr8JeqRN9jHDGAXCQrQjm4AUnwHnJU9O3O8CFjhUuSqVrqY3myJPN1g0T8INvF5KYzUk9Zhgp18vYeY8/TqpJbcGT3aXeIFa87LXEPk7SruPjbtUjvmqlXp8ADLXIwE6vVpLveutto1RCtp72XKc1poL7nS5BmLW5efeqJqApNx/o32sTh9ZtRpMj5+GZDr8ZPGEG5hX6ZtMqee3NtANpTgm4ocAO0kYl+kwnWJtP/Z/QceCd5NLKzzLVohNE+KlDsTTz7u0TsazOsaPPYZ2P+tO5nuFkTwA/E4aXHhc4PvyOOnREDdN24ij3owEE/tv+37i+ZWdSdTDnQMV7XzgsbmtsQbYNp2EAaiQvbDHCYmpABXRzkdwsYhIsHy535s9xed890gtcwrecqHOaUt09THpReh8i6pphVTqEcVCb+VdkoLzekbMFRhYIOlykpVpXF8rcx5owrET91UjGsoQ2ZxTwvJRTgnmOwjzGsZNxAcW2EIhPtysfhMLR mykey@host"} >> "$GITHUB_OUTPUT"
+          echo sshkey=${KEY_INPUT:-"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQC6cZ/ZGVD547VMy4Cz/sMVAezZsv33woT8v9zCh0WuSIcMZOFIeBhI7oB6L7hwSlGmb2BNFmgJJ5ML0jy6y55rI1X0EaQV9uLTdYcfpcFUu0sbq5/9TAEWqt5EL8R7nxs7Yl8FEfUhG4GAMiDUwJK9oOIHvtzjqdCNYZKOB5JyVc3/tBqtUXbMrGP+ZLuqscxLrdbgQRg6FTOXt8jW48ofYa7nM7tMoFBXIN7wSCPpifme7HnoblHIeoPlGwyLPEiu36pnj6KAKQCZgYenx8Noj99+nnFJorxbtgIL7WMWjt+HlVaiVEZ6A6MbaZbwrhpCiow57bd3zdq3vluZwPZNNCL8AOKXtm7D35aC+wKibur7FyundFNlKpHgTtXRYNEKRj/ulW1z2HKwoU6Ban6X+rSzVmGkBiQyB/G76L8b/eXRh3Hptvbp4nQu15kGhsQXZA7g7Z25yPlmeO7pWMRJRNbohhOM/29PX1c6dH9+WoNJtkHh6Hk1fgTD0JDVxNFarIjmxv0nIQUcr0tdsL2/3o0t7sZwjtZvoFSGqKsZ5PMAqUHjJiDnGwK+GDBOoWWtrtkJXNfSxwl0Zsazj6tN4CG29sUjzss9LWcNTa8zdUhb3RY6OhpWcQaBJi/MmQVKLacwy+KxKfhMEXmNkaVWyX3eCaK1ih9q7wWM6iDWX1pJkmKlroXmRzVaSgfNb1JIRkBtiecOHN+26Bv59TbJcKkYXsbBP6P4m5VqjiJD2xw/VN6sW8Kohu9igBtxNR4ayYqKyIRPE5UbE/kl4x+84C//IfKdnRoLmCwkUauOC8z/5ThMmlASAtIOgAcdQSJRXWyWtQoZnDc5Om3SCejqflkBceQpr8JeqRN9jHDGAXCQrQjm4AUnwHnJU9O3O8CFjhUuSqVrqY3myJPN1g0T8INvF5KYzUk9Zhgp18vYeY8/TqpJbcGT3aXeIFa87LXEPk7SruPjbtUjvmqlXp8ADLXIwE6vVpLveutto1RCtp72XKc1poL7nS5BmLW5efeqJqApNx/o32sTh9ZtRpMj5+GZDr8ZPGEG5hX6ZtMqee3NtANpTgm4ocAO0kYl+kwnWJtP/Z/QceCd5NLKzzLVohNE+KlDsTTz7u0TsazOsaPPYZ2P+tO5nuFkTwA/E4aXHhc4PvyOOnREDdN24ij3owEE/tv+37i+ZWdSdTDnQMV7XzgsbmtsQbYNp2EAaiQvbDHCYmpABXRzkdwsYhIsHy535s9xed890gtcwrecqHOaUt09THpReh8i6pphVTqEcVCb+VdkoLzekbMFRhYIOlykpVpXF8rcx5owrET91UjGsoQ2ZxTwvJRTgnmOwjzGsZNxAcW2EIhPtysfhMLR mykey@host"} >> "$GITHUB_OUTPUT"
           IMG_INPUT=${{ github.event.inputs.image }}
           MYIMG=${IMG_INPUT:-"https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.1-x86_64-bios-cloudinit-r0.qcow2"}
           echo "image=${IMG_INPUT:-"https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.1-x86_64-bios-cloudinit-r0.qcow2"}" >> "$GITHUB_OUTPUT"
@@ -290,8 +290,8 @@ jobs:
             ${{ steps.valuesprep.outputs.cdrom }}
             -boot
             ${{ steps.valuesprep.outputs.boot }}
-#         run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;tail -f -r  /tmp/guest.out &  test -e TMP_SCRIPT && bash TMP_SCRIPT;  echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
-          run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;tail -f -r  /tmp/guest.out &  test -e TMP_SCRIPT && bash TMP_SCRIPT; echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
+#         run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;tail -f --retry  /tmp/guest.out &  test -e TMP_SCRIPT && bash TMP_SCRIPT;  echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
+          run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;tail -f --retry  /tmp/guest.out &  test -e TMP_SCRIPT && bash TMP_SCRIPT; echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
 
 
 # echo 'screen -dmS sshj ash -c "while (true);do ssh qemukvmtest@ssh-j.com -N -R qemukvm:22:localhost:22 ;done" & '          
