runmode

diff --git a/.github/workflows/kvm.yml b/.github/workflows/kvm.yml
--- a/.github/workflows/kvm.yml
+++ b/.github/workflows/kvm.yml
@@ -270,8 +270,8 @@ jobs:
 #            :1
 #            -boot
 #            ${{ steps.valuesprep.outputs.bootorder }}
-#         run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
-          run: test -e ~/.ssh|mkdir ~/.ssh;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
+#         run: test -e ~/.ssh|| mkdir ~/.ssh|| true ;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo timmy;sleep 1;echo password111 ;sleep 5;echo 'doas ash -c "echo asd;test -e /dev/ttyS0 && echo in_term_ttyS0 >>/dev/ttyS0 ; test -e /dev/ttyAMA0 && echo in_term_ttyAMA0 >> /dev/ttyAMA0; ln -s /tmp/tsocks.conf /etc/; apk add tor tsocks screen curl socat bash"';sleep 1 ; echo password ;sleep 1;echo bash;sleep 1;cat serialscript;sleep 3) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60; while (ps -ALFc|grep -v grep |grep qemu|grep  kvm |grep 8192);do sleep 60 ;echo -n .;done"
+          run: test -e ~/.ssh|| mkdir ~/.ssh|| true ;echo "${{ steps.valuesprep.outputs.sshkey }}" > .ssh/authorized_keys;echo provisioning from ${{ steps.valuesprep.outputs.myip }} ; echo ${{ steps.valuesprep.outputs.myip }} > /tmp/myip ;sleep 10 ;( tail -f --retry  /tmp/guest.out || tail -f  /tmp/guest.out ) &  test -e TMP_SCRIPT && bash TMP_SCRIPT || true ;  docker ps -a ;echo  > /tmp/guest.in  ;sleep 42 ; ( echo ) > /tmp/guest.in & sleep 20;bash -c "ps -ALFc|grep qemu;ps w|grep qemu;sleep 60;counter="0"; while ((echo |nc 127.0.0.1 2222)|grep -i ssh -q|| exit 1);do  counter=$(($counter + 1 ));[[ $(($counter % 10 )) -eq 0 ]] && echo ; sleep 60 ;echo -n .;done"
 
 # echo 'screen -dmS sshj ash -c "while (true);do ssh qemukvmtest@ssh-j.com -N -R qemukvm:22:localhost:22 ;done" & '          
 #            -smbios
